input Character {
  name: String!
}

type Deity {
  name: String!
  worships: Deity
  power: Power!
}

enum Power {
  Lightning
  Teleportation
  Omniscience
}

# type Query {
#   _dummy: String!
#   deity: Deity
#   name: String!
#   power: Power!
# }

type GetHero {
  deity(fatherOf: Character): Deity!
}

type Query {
  query: GetHero
}

schema {
  query: GetHero
}
